name: Cypress E2E

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 180
          browser: chrome